module.exports = {
  KEY_TYPE: 'type',
  KEY_VALUE: 'value',
  KEY_PORT_WS: 'port-ws',
  KEY_PORT_RPC: 'port-rpc',
  KEY_ENDPOINT: 'endpoint',
  KEY_HOST: 'host',
  KEY_PORT: 'port',
  KEY_TIMEOUT: 'timeout',
  KEY_LIGHT_CLIENTS: 'light-clients',
  KEY_COMMITMENT: 'commitment',
  KEY_SIGNATURE: 'signature',
  KEY_PUBLICKEY: 'publicKey',
  KEY_CERTIFICATECHAIN: 'certificateChain',
}
